version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    container_name: microservices-houses-mysql
    restart: always
    environment:
      MYSQL_DATABASE: stock
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
